# python:
# - python
# - py
# sql:
# - sql
# - postgres
# - mysql
# aws:
# - aws
# - amazon web services
# pandas:
# - pandas
# etl:
# - etl

required:
  - sql
  - python
preferred:
  # - airflow
  - elt
  - etl
  - agile
  - ci/cd
  # - dbt
  - spark
  - aws
  - databricks
titles:
  - data engineer
  # - analytics engineer
  - data analyst
  - business intelligence
